export const WEATHER_DATA_REQUEST = 'WEATHER_DATA_REQUEST';
export const WEATHER_DATA_SUCCESS = 'WEATHER_DATA_SUCCESS';
export const WEATHER_DATA_FAILURE = 'WEATHER_DATA_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

// export const SIGNED_IN = 'SIGNED_IN';
// export const SIGNED_OUT = 'SIGNED_OUT';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const CHECK_LOGIN_REQUEST = 'CHECK_LOGIN_REQUEST';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAILURE = 'CHECK_LOGIN_FAILURE';


export const HISTORY_DATA_REQUEST = 'HISTORY_DATA_REQUEST';
export const HISTORY_DATA_SUCCESS = 'HISTORY_DATA_SUCCESS';
export const HISTORY_DATA_FAILURE = 'HISTORY_DATA_FAILURE';
